# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Egor\Desktop\SigCheck\design.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(791, 252)
        MainWindow.setMinimumSize(QtCore.QSize(791, 252))
        MainWindow.setMaximumSize(QtCore.QSize(791, 252))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(140, 140, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.CouplingCheck = QtWidgets.QCheckBox(self.centralwidget)
        self.CouplingCheck.setGeometry(QtCore.QRect(20, 140, 91, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.CouplingCheck.setFont(font)
        self.CouplingCheck.setChecked(True)
        self.CouplingCheck.setObjectName("CouplingCheck")
        self.FilesPath = QtWidgets.QLineEdit(self.centralwidget)
        self.FilesPath.setGeometry(QtCore.QRect(150, 20, 151, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.FilesPath.setFont(font)
        self.FilesPath.setPlaceholderText("")
        self.FilesPath.setObjectName("FilesPath")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 20, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 50, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.SigPath = QtWidgets.QLineEdit(self.centralwidget)
        self.SigPath.setGeometry(QtCore.QRect(150, 50, 151, 20))
        self.SigPath.setObjectName("SigPath")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 110, 171, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.FragSize = QtWidgets.QLineEdit(self.centralwidget)
        self.FragSize.setGeometry(QtCore.QRect(200, 110, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.FragSize.setFont(font)
        self.FragSize.setInputMask("")
        self.FragSize.setText("")
        self.FragSize.setClearButtonEnabled(False)
        self.FragSize.setObjectName("FragSize")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 80, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.TablesPath = QtWidgets.QLineEdit(self.centralwidget)
        self.TablesPath.setGeometry(QtCore.QRect(150, 80, 151, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.TablesPath.setFont(font)
        self.TablesPath.setText("")
        self.TablesPath.setPlaceholderText("")
        self.TablesPath.setClearButtonEnabled(False)
        self.TablesPath.setObjectName("TablesPath")
        self.StarValue = QtWidgets.QLineEdit(self.centralwidget)
        self.StarValue.setGeometry(QtCore.QRect(180, 140, 81, 20))
        self.StarValue.setPlaceholderText("")
        self.StarValue.setObjectName("StarValue")
        self.StartButton = QtWidgets.QPushButton(self.centralwidget)
        self.StartButton.setEnabled(False)
        self.StartButton.setGeometry(QtCore.QRect(170, 190, 131, 41))
        self.StartButton.setObjectName("StartButton")
        self.fileButton = QtWidgets.QPushButton(self.centralwidget)
        self.fileButton.setGeometry(QtCore.QRect(310, 20, 91, 23))
        self.fileButton.setObjectName("fileButton")
        self.signatureButton = QtWidgets.QPushButton(self.centralwidget)
        self.signatureButton.setGeometry(QtCore.QRect(310, 50, 91, 23))
        self.signatureButton.setObjectName("signatureButton")
        self.outputButton = QtWidgets.QPushButton(self.centralwidget)
        self.outputButton.setGeometry(QtCore.QRect(310, 80, 91, 23))
        self.outputButton.setObjectName("outputButton")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(420, 20, 351, 211))
        self.textBrowser.setObjectName("textBrowser")
        self.okButton = QtWidgets.QPushButton(self.centralwidget)
        self.okButton.setGeometry(QtCore.QRect(20, 190, 131, 41))
        self.okButton.setObjectName("okButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Signature counter"))
        self.label.setText(_translate("MainWindow", "* ="))
        self.CouplingCheck.setText(_translate("MainWindow", "Зацепление"))
        self.label_2.setText(_translate("MainWindow", "Путь к файлам:"))
        self.label_3.setText(_translate("MainWindow", "Путь к сигнатурам:"))
        self.SigPath.setPlaceholderText(_translate("MainWindow", "Текстовый файл"))
        self.label_4.setText(_translate("MainWindow", "Размер фрагмента в байтах:"))
        self.FragSize.setPlaceholderText(_translate("MainWindow", "0 - весь файл"))
        self.label_5.setText(_translate("MainWindow", "Экспорт таблиц в:"))
        self.StarValue.setText(_translate("MainWindow", "1"))
        self.StartButton.setText(_translate("MainWindow", "Start"))
        self.fileButton.setText(_translate("MainWindow", "Выбрать папку"))
        self.signatureButton.setText(_translate("MainWindow", "Выбрать папку"))
        self.outputButton.setText(_translate("MainWindow", "Выбрать папку"))
        self.okButton.setText(_translate("MainWindow", "OK"))

